#!/bin/bash
temp=$(cat /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp1_input)
declare -A tempIcons=([0]="" [0.25]="" [0.50]="" [0.75]="" [1.00]="")

case $1 in
"icon")
    if [[ $(cat /sys/class/power_supply/BAT0/status) == "Charging" ]]; then
        echo "${battery_charging[$idx]}"
        # increment idx by 0.25
        idx=$(calc $idx + 0.25)
        # if idx is more than 1 then reset to 0
        if [[ $(bc <<<"$idx > 1.00") -eq 1 ]]; then
            idx=0
        fi
        # echo $key
        eww update batteryIconIndex=$idx
    elif [[ $(cat /sys/class/power_supply/BAT0/status) == "Full" ]]; then
        echo " Full"
    else
        echo "${battery_discharging[$idx]}"
        idx=$(calc $idx + 0.25)
        # if idx is more than 1 then reset to 0
        if [[ $(bc <<<"$idx > 1.00") -eq 1 ]]; then
            idx=0
        fi
        eww update batteryIconIndex=$idx
    fi
    ;;
"temp")
    echo $temp
    ;;
esac
