#!/bin/bash
temp=$(cat /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp1_input)
# divide temp by 1000
temp=$(($temp / 1000))
declare -a tempIcons=(
    #0   1   2   3   4
    "" "" "" "" ""
    "" "" "" "" ""
    "" "" "" "" ""
    "" "" "" "" ""
    ""
)
declare -a tempColors=(
    #    0       1         2         3        4
    "#6CCB6E" "#6CCB6E" "#6CCB6E" "#6CCB6E" "#6CCB6E"
    "#6CCB6E" "#6CCB6E" "#6CCB6E" "#6CCB6E" "#6CCB6E"
    "#7FE4D2" "#7FE4D2" "#7FE4D2" "#FB6396" "#FB6396"
    "#FB6396" "#FB6396" "#F92D72" "#F92D72" "#F92D72"
    "#F92D72"
)
case $1 in
"icon")
    if [[ $temp -gt 100 ]]; then
        echo "${tempIcons[9]}"

    else
        idx=$(($temp / 5))
        # echo $idx
        echo "${tempIcons[$idx]}"
    fi
    ;;
"temp")
    echo "$temp°C"
    ;;
"color")
    idx=$(($temp / 5))
    echo "${tempColors[$idx]}"
    ;;
esac
