#!/bin/sh

# Check for the available wifi interface (Wifi for now will add ethernet support soon) making it dynamic
INTERFACE=$(iw dev | awk '$1=="Interface"{print $2}')

symbol() {
    [ $(cat /sys/class/net/w*/operstate) = down ] && echo 睊 && exit
    echo 
}

name() {
    nmcli | grep $INTERFACE | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

current_status() {
    [ $(cat /sys/class/net/w*/operstate) = down ] && echo 0 && exit
    echo 1
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
[ "$1" = "status" ] && current_status && exit
