#!/bin/sh

# Set playerctl to check for spotify first priority, and any player at second priority, and make the browser the last priority
PLAYER=$(playerctl -p spotify,%any,firefox,chromium,brave,mpd status)

if [ "$PLAYER" = "Playing" ]; then
    # STATUS=""
    STATUS=1
elif [ "$PLAYER" = "Paused" ]; then
    # STATUS=""
    STATUS=0
else
    # STATUS=""
    STATUS=0
fi

echo $STATUS
